version: '2.1'

services:
  galera-0:
    image: docker.io/bitnami/mariadb-galera:10.5
    ports:
      - 3001:3306
    networks:
      galera_net:
        ipv4_address: 172.20.128.1
        aliases:
          - galera-0
    env_file:
      - galera-bootstrap.env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  galera-1:
    image: docker.io/bitnami/mariadb-galera:10.5
    ports:
      - 3002:3306
    networks:
      galera_net:
        ipv4_address: 172.20.128.2
        aliases:
          - galera-1
    env_file:
      - galera-slave.env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      galera-0:
        condition: service_healthy

  galera-2:
    image: docker.io/bitnami/mariadb-galera:10.5
    ports:
      - 3003:3306
    networks:
      galera_net:
        ipv4_address: 172.20.128.3
        aliases:
          - galera-2
    env_file:
      - galera-slave.env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      galera-0:
        condition: service_healthy

  haproxy_1:
    build: .
    image: haproxy_keepalived:latest
    restart: on-failure
    ports:
      - 30000:30000
    networks:
      galera_net:
        ipv4_address: 172.20.128.11
    cap_add:
      - NET_ADMIN
    env_file:
      - haproxy.env
    volumes:
      - ./haproxy_1.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./keepalived_1.conf:/etc/keepalived/keepalived.conf
    depends_on:
      galera-0:
        condition: service_healthy
      galera-1:
        condition: service_healthy
      galera-2:
        condition: service_healthy
    healthcheck:
      test: "/bin/pidof haproxy"
      interval: 15s
      timeout: 5s
      retries: 6

  haproxy_2:
    build: .
    image: haproxy_keepalived:latest
    restart: on-failure
    ports:
      - 30001:30000
    networks:
      galera_net:
        ipv4_address: 172.20.128.12
    cap_add:
      - NET_ADMIN
    volumes:
      - ./haproxy_2.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./keepalived_2.conf:/etc/keepalived/keepalived.conf
    depends_on:
      galera-0:
        condition: service_healthy
      galera-1:
        condition: service_healthy
      galera-2:
        condition: service_healthy
    healthcheck:
      test: "/bin/pidof haproxy"
      interval: 15s
      timeout: 5s
      retries: 6

  monitor:
    image: haproxy:2.2.2-alpine
    ports:
      - 3306:3306
    volumes:
      - ./haproxy_dev.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - galera_net
    depends_on:
      haproxy_1:
        condition: service_healthy
      haproxy_2:
        condition: service_healthy

networks:
  galera_net:
    ipam:
      config:
        - subnet: 172.20.128.0/16
