version: "3.6"

x-env-files: &env-files
  env_file:
    - .env

services:
  mysql-manager-1:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd

  mysql-manager-2:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd

  data-node-1:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd

  data-node-2:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd

  mysql-server-1:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: mysqld
    ports:
      - 3306:3306

  mysql-server-2:
    image: mysql/mysql-cluster:7.5
    <<: *env-files
    networks:
      - my-cluster
    restart: "always"
    volumes:
      - ./cnf/my.cnf:/etc/my.cnf
      - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: mysqld
    ports:
      - 3307:3306

networks:
  my-cluster:
    ipam:
      config:
        - subnet: 172.18.0.0/16
